[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "Read@louds"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/ashutoshmjain/shutri"
cname = "www.shutri.com"
no-section-label = true
